image: cenote/jasperstarter-env

pipelines:
  default:
    - step:
        script:
          - mvn clean package -P snapshot,windows-setup
          # upload new artifact to sourceforge downloads
          - ssh-keyscan -t rsa ${SF_HOST} >>  ~/.ssh/known_hosts
          - (umask 077; echo $SF_SSH_BASE64 | base64 --decode > ~/.ssh/id_rsa)
          - scp target/*.zip ${SF_USER}@${SF_HOST}:${SF_FILEBASE}/snapshots/
          # upload new artifact to bitbucket downloads
          - ARTIFACT=$(ls -1 target/*.zip|head -n1)
          - ARTIFACT_BASENAME=$(basename $ARTIFACT)
          - curl -X POST -v --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"${ARTIFACT}"

  tags:
    '*-*':
      - step:
          script:
            - mvn clean package -P release,windows-setup
            # upload release artifacts to sourceforge 
            - bash bitbucket-release-to-sourceforge.bash

  branches:
    java9*:
      - step:
          image: cenote/xenial-java9
          script:
            - mvn -version
            - mvn clean package -P snapshot,windows-setup -Dmaven.test.skip=true
            - mvn test
            # upload new artifact to sourceforge downloads
            - ssh-keyscan -t rsa ${SF_HOST} >>  ~/.ssh/known_hosts
            - (umask 077; echo $SF_SSH_BASE64 | base64 --decode > ~/.ssh/id_rsa)
            - scp target/*.zip ${SF_USER}@${SF_HOST}:${SF_FILEBASE}/snapshots/
            # upload new artifact to bitbucket downloads
            - ARTIFACT=$(ls -1 target/*.zip|head -n1)
            - ARTIFACT_BASENAME=$(basename $ARTIFACT)
            - curl -X POST -v --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"${ARTIFACT}"
